# Generated by Django 4.2.4 on 2023-08-03 20:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ShoppingCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('image', models.ImageField(upload_to='shoppercenter')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=30)),
                ('location', models.TextField(blank=True, null=True)),
                ('address_line_1', models.CharField(max_length=50)),
                ('state', models.CharField(help_text='Two capital letters to refer to a State e.g. FL (Florida)', max_length=2, null=True, validators=[django.core.validators.RegexValidator(regex='^[A-Z]{2}$')])),
                ('address_line_2', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(max_length=28)),
                ('zip_code', models.CharField(max_length=9)),
                ('description', models.TextField(max_length=280)),
                ('image', models.ImageField(upload_to='retail')),
                ('origin', models.CharField(choices=[('CLOVER', 'CLOVER'), ('SQUARE', 'SQUARE')], max_length=7)),
                ('app_id', models.CharField(max_length=50)),
                ('app_secret', models.CharField(max_length=100)),
                ('merchant_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('access_token', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=100, null=True))),
                ('refresh_token', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=100, null=True))),
                ('token_type', models.CharField(blank=True, max_length=50, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expiration Date')),
                ('square_csrf', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.ManyToManyField(to='retailer.category')),
                ('shopping_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='retailer.shoppingcenter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
