# Generated by Django 4.2.4 on 2023-08-08 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('retailer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(choices=[('candle', 'candle'), ('bakery_dining', 'bakery_dining'), ('checkroom', 'checkroom'), ('storefront', 'storefront'), ('content_cut', 'content_cut'), ('restaurant', 'restaurant')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='retailer',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shoppingcenter',
            name='category',
            field=models.ManyToManyField(to='retailer.category'),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='shopping_center',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='retailer.shoppingcenter'),
        ),
    ]
