# Generated by Django 4.2.3 on 2023-08-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0002_alter_category_options_category_icon_retailer_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailer',
            name='app_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='app_secret',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
