# Generated by Django 4.2.3 on 2023-08-11 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0004_alter_retailer_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Cetegory', 'verbose_name_plural': 'Categories'},
        ),
    ]
