# Generated by Django 4.2.3 on 2023-08-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0005_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailer',
            name='app_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='app_secret',
            field=models.CharField(max_length=100),
        ),
    ]
