# Generated by Django 4.2.3 on 2023-08-14 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0006_alter_retailer_app_id_alter_retailer_app_secret'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
