# Generated by Django 4.2.3 on 2023-08-17 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0007_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='retailer',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='shoppingcenter',
            name='is_active',
        ),
    ]
