# Generated by Django 4.2.3 on 2023-08-28 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0008_remove_category_is_active_remove_retailer_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailer',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='retailer',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='retailer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='retailer',
            name='location',
        ),
        migrations.RemoveField(
            model_name='retailer',
            name='state',
        ),
        migrations.RemoveField(
            model_name='retailer',
            name='zip_code',
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(blank=True, max_length=100, null=True)),
                ('address3', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
                ('pos_id', models.CharField(blank=True, max_length=100, null=True)),
                ('retailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='retailer.retailer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
