# Generated by Django 4.2.3 on 2023-09-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retailer", "0009_remove_retailer_address_line_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="retailer",
            name="is_sync",
            field=models.BooleanField(default=False),
        ),
    ]
