# Generated by Django 4.2.3 on 2023-10-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retailer", "0010_retailer_is_sync"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="address1",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="location",
            name="address2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="address3",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
