# Generated by Django 4.2.3 on 2023-11-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0012_help_text_includes'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailer',
            name='token_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Token Creation Date'),
        ),
    ]
