# Generated by Django 4.2.3 on 2023-10-27 18:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("retailer", "0012_help_text_includes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="retailer",
            name="user",
        ),
    ]
