# Generated by Django 4.2.3 on 2023-10-30 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retailer", "0012_help_text_includes"),
    ]

    operations = [
        migrations.AddField(
            model_name="retailer",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
