# Generated by Django 4.2.3 on 2023-11-03 16:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("retailer", "0013_remove_retailer_user"),
        ("retailer", "0013_retailer_is_approved"),
        ("retailer", "0013_retailer_token_created_at"),
    ]

    operations = []
