# Generated by Django 4.2.3 on 2023-11-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0014_merge_20231103_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
