# Generated by Django 4.2.3 on 2024-09-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retailer", "0015_retailer_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retailer",
            name="email",
            field=models.EmailField(
                blank=True, db_index=True, max_length=254, verbose_name="email address"
            ),
        ),
    ]
