# Generated by Django 4.2.3 on 2024-09-27 06:25

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):
    dependencies = [
        ("retailer", "0016_alter_retailer_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="retailer",
            name="is_approved",
        ),
        migrations.AddField(
            model_name="retailer",
            name="note",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="retailer",
            name="status",
            field=models.CharField(
                choices=[
                    ("requesting", "requesting"),
                    ("approved", "approved"),
                    ("denied", "denied"),
                ],
                db_index=True,
                default="requesting",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="retailer",
            name="access_token",
            field=django_cryptography.fields.encrypt(
                models.CharField(blank=True, db_index=True, max_length=100, null=True)
            ),
        ),
        migrations.AlterField(
            model_name="retailer",
            name="app_id",
            field=models.CharField(
                db_index=True,
                help_text="Please carefully review the entered value to ensure it is correct.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="retailer",
            name="merchant_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=50, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="retailer",
            name="origin",
            field=models.CharField(
                choices=[("CLOVER", "CLOVER"), ("SQUARE", "SQUARE")],
                db_index=True,
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="retailer",
            name="refresh_token",
            field=django_cryptography.fields.encrypt(
                models.CharField(blank=True, db_index=True, max_length=100, null=True)
            ),
        ),
        migrations.AlterField(
            model_name="retailer",
            name="token_type",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
