# Generated by Django 4.2.3 on 2024-11-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retailer", "0017_remove_retailer_is_approved_retailer_note_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="zip_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
