# Generated by Django 4.2.3 on 2024-11-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retailer", "0018_alter_location_city_alter_location_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="address1",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
