# Generated by Django 4.2.3 on 2024-11-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retailer", "0019_alter_location_address1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retailer",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="retail"),
        ),
    ]
