# Generated by Django 4.2.3 on 2025-04-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retailer", "0021_alter_retailer_origin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retailer",
            name="origin",
            field=models.CharField(
                choices=[
                    ("CLOVER", "CLOVER"),
                    ("SQUARE", "SQUARE"),
                    ("Self Manage", "Self Manage"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
