# Generated by Django 4.2.3 on 2023-08-17 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0002_category_inventory_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='is_active',
        ),
    ]
