# Generated by Django 4.2.3 on 2023-08-18 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0004_alter_inventory_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('name', models.CharField(max_length=50)),
                ('sku', models.CharField(blank=True, max_length=20, null=True)),
                ('upc', models.CharField(blank=True, max_length=20, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('origin_id', models.CharField(max_length=50)),
                ('origin_parent_id', models.CharField(max_length=50)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('inventory', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventories.inventory')),
            ],
            options={
                'verbose_name': 'Variant',
                'verbose_name_plural': 'Variations',
            },
        ),
    ]
