# Generated by Django 4.2.3 on 2023-08-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0005_variant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='quantity',
            new_name='origin_category_id',
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='name',
            new_name='product_name',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='price',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='product_title',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='upc',
        ),
        migrations.AddField(
            model_name='inventory',
            name='description_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='description_raw',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='origin_id',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='product_name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='origin_id',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='origin_parent_id',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
