# Generated by Django 4.2.3 on 2023-08-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0006_rename_quantity_inventory_origin_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='origin_category_id',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
