# Generated by Django 4.2.3 on 2023-08-19 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0008_remove_category_is_active_remove_retailer_is_active_and_more'),
        ('inventories', '0007_alter_inventory_origin_category_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inventory',
            new_name='Product',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='inventory',
            new_name='Product',
        ),
    ]
