# Generated by Django 4.2.3 on 2023-08-19 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0008_rename_inventory_product_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='Product',
            new_name='product',
        ),
    ]
