# Generated by Django 4.2.3 on 2023-08-19 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0008_remove_category_is_active_remove_retailer_is_active_and_more'),
        ('inventories', '0009_rename_product_variant_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='retailer',
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('name', models.CharField(default=None, max_length=50, null=True)),
                ('retailer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='retailer.retailer')),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventories',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventories.inventory'),
        ),
    ]
