# Generated by Django 4.2.3 on 2023-08-20 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0011_alter_product_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='product_name',
            new_name='name',
        ),
    ]
