# Generated by Django 4.2.3 on 2023-08-21 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0012_rename_product_name_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
