# Generated by Django 4.2.3 on 2023-08-21 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0013_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='origin',
            field=models.CharField(choices=[('CLOVER', 'CLOVER'), ('SQUARE', 'SQUARE')], default=None, max_length=10, null=True),
        ),
    ]
