# Generated by Django 4.2.3 on 2023-08-24 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0014_product_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='category',
            name='origin_id',
        ),
    ]
