# Generated by Django 4.2.3 on 2023-08-24 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventories', '0014_product_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('origin_id', models.CharField(max_length=100, null=True)),
                ('origin', models.CharField(choices=[('CLOVER', 'CLOVER'), ('SQUARE', 'SQUARE')], default=('SQUARE', 'SQUARE'), max_length=7)),
                ('paylod', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='SUCCESS', max_length=20)),
                ('quantity', models.IntegerField(default=0)),
                ('time_limit', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventories.product')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
            },
        ),
    ]
