# Generated by Django 4.2.3 on 2023-08-25 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0016_alter_reservation_product_alter_reservation_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='paylod',
            new_name='payload',
        ),
    ]
