# Generated by Django 4.2.3 on 2023-08-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0017_rename_paylod_reservation_payload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='payload',
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
