# Generated by Django 4.2.3 on 2023-08-25 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0015_remove_category_origin_remove_category_origin_id'),
        ('inventories', '0018_remove_reservation_payload_and_more'),
    ]

    operations = [
    ]
