# Generated by Django 4.2.3 on 2023-08-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0019_merge_20230825_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='quantity',
            new_name='stock',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='origin',
            field=models.CharField(choices=[('CLOVER', 'CLOVER'), ('SQUARE', 'SQUARE')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='origin_id',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
