# Generated by Django 4.2.3 on 2023-08-29 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0009_remove_retailer_address_line_1_and_more'),
        ('inventories', '0020_rename_quantity_variant_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='retailer',
        ),
        migrations.AddField(
            model_name='inventory',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='retailer.location'),
        ),
    ]
