# Generated by Django 4.2.3 on 2023-08-29 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0021_remove_inventory_retailer_inventory_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='product',
        ),
        migrations.AddField(
            model_name='reservation',
            name='variant',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventories.variant'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='product',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='inventories.product'),
        ),
    ]
