# Generated by Django 4.2.3 on 2023-08-30 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0022_remove_reservation_product_reservation_variant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='image',
        ),
        migrations.CreateModel(
            name='VariantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.variant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
