# Generated by Django 4.2.3 on 2023-08-30 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0023_remove_variant_image_variantimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='origin_category_id',
        ),
    ]
