# Generated by Django 4.2.3 on 2023-09-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0025_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description_raw',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_html',
        ),
        migrations.AddField(
            model_name='variant',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantimage',
            name='image_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='variantimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='inventories'),
        ),
    ]
