# Generated by Django 4.2.3 on 2023-09-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0026_rename_description_raw_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='is_modified_by_admin',
            field=models.BooleanField(default=False, verbose_name='Has Admin modified this variant'),
        ),
    ]
