# Generated by Django 4.2.3 on 2023-09-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0027_variant_is_modified_by_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='is_modified_by_admin',
            field=models.BooleanField(default=False, verbose_name='Modified by Wyndo Admin'),
        ),
    ]
