# Generated by Django 4.2.3 on 2023-09-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventories", "0028_alter_variant_is_modified_by_admin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="description",
        ),
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
        migrations.AlterField(
            model_name="variant",
            name="is_modified_by_admin",
            field=models.BooleanField(default=False, verbose_name="Modified by Wyndo"),
        ),
    ]
