# Generated by Django 4.2.3 on 2023-09-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "inventories",
            "0029_remove_product_description_remove_product_image_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="total_stock",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
