# Generated by Django 4.2.3 on 2023-09-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0030_product_total_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_modified_by_admin',
            field=models.BooleanField(default=False, help_text="When activated the name won't be updated by the app", verbose_name='Modified by Wyndo'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='is_modified_by_admin',
            field=models.BooleanField(default=False, help_text="When activated the description and name won't be updated by the app", verbose_name='Modified by Wyndo'),
        ),
    ]
