# Generated by Django 4.2.3 on 2023-09-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventories", "0031_product_is_modified_by_admin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
