# Generated by Django 4.2.3 on 2023-09-26 15:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventories", "0032_product_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="variant",
            options={
                "verbose_name": "Product Detail",
                "verbose_name_plural": "Variations",
            },
        ),
    ]
