# Generated by Django 4.2.3 on 2023-09-30 00:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventories", "0033_alter_variant_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
