# Generated by Django 4.2.3 on 2023-10-03 00:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventories", "0033_alter_variant_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
