# Generated by Django 4.2.3 on 2023-10-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventories", "0034_reservation_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variant",
            name="stock",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
