# Generated by Django 4.2.3 on 2023-10-04 15:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventories", "0034_alter_product_name"),
        ("inventories", "0035_alter_variant_stock"),
    ]

    operations = []
