# Generated by Django 4.2.3 on 2023-10-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inventories', '0036_merge_20231004_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='description',
            field=models.TextField(null=True, blank=True),
        ),
    ]
