# Generated by Django 4.2.3 on 2023-10-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventories", "0037_auto_20231005_1234"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variantimage",
            name="image_id",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
