# Generated by Django 4.2.3 on 2023-10-23 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0038_alter_variantimage_image_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('origin_id', 'inventory')},
        ),
    ]
