# Generated by Django 4.2.3 on 2023-10-30 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0039_alter_product_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
