# Generated by Django 4.2.3 on 2023-11-28 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0015_retailer_email'),
        ('inventories', '0040_alter_variant_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='retailer.location', unique=True),
        ),
    ]
