# Generated by Django 4.2.3 on 2024-09-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventories", "0041_alter_inventory_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active Status"),
        ),
    ]
