# Generated by Django 4.2.3 on 2024-10-07 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("retailer", "0017_remove_retailer_is_approved_retailer_note_and_more"),
        ("inventories", "0043_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="origin_id",
            field=models.CharField(default=None, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="retailer",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customers",
                to="retailer.retailer",
            ),
        ),
    ]
