# Generated by Django 4.2.3 on 2024-10-07 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventories", "0044_customer_origin_id_alter_customer_retailer"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventories.customer",
            ),
        ),
    ]
