# Generated by Django 4.2.3 on 2024-10-08 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("retailer", "0017_remove_retailer_is_approved_retailer_note_and_more"),
        ("inventories", "0045_reservation_customer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="variant",
        ),
        migrations.AddField(
            model_name="reservation",
            name="retailer",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservations",
                to="retailer.retailer",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservations",
                to="inventories.customer",
            ),
        ),
        migrations.CreateModel(
            name="ReservationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated date"),
                ),
                ("quantity", models.IntegerField(default=0)),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservation_items",
                        to="inventories.reservation",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservation_items",
                        to="inventories.variant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reservation Item",
                "verbose_name_plural": "Reservation Items",
            },
        ),
    ]
