# Generated by Django 4.2.3 on 2024-10-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "inventories",
            "0047_alter_customer_address1_alter_customer_address2_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="origin_id",
            field=models.CharField(default=None, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservation_code",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
