# Generated by Django 4.2.3 on 2024-10-10 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventories", "0048_alter_reservation_origin_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation",
            options={"verbose_name": "Order", "verbose_name_plural": "Orders"},
        ),
        migrations.AddField(
            model_name="reservation",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="reservation",
            name="order_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="reservation",
            name="tax",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="reservationitem",
            name="tax",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="reservationitem",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="reservationitem",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="reservationitem",
            name="variation_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.CreateModel(
            name="ReservationPickup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated date"),
                ),
                (
                    "recipient_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("pickup_time", models.DateTimeField(blank=True, null=True)),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservation_pickups",
                        to="inventories.reservation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reservation Pickup",
                "verbose_name_plural": "Reservation Pickups",
            },
        ),
    ]
