# Generated by Django 4.2.3 on 2024-10-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventories", "0049_alter_reservation_options_reservation_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservationpickup",
            name="origin_id",
            field=models.CharField(default=None, max_length=50, null=True, unique=True),
        ),
    ]
