# Generated by Django 4.2.3 on 2024-10-15 08:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventories", "0050_reservationpickup_origin_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservationpickup",
            options={"verbose_name": "Pickup", "verbose_name_plural": "Pickup"},
        ),
    ]
