# Generated by Django 4.2.3 on 2024-10-15 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("retailer", "0017_remove_retailer_is_approved_retailer_note_and_more"),
        ("inventories", "0051_alter_reservationpickup_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated date"),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "origin_id",
                    models.CharField(
                        default=None, max_length=50, null=True, unique=True
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[("CLOVER", "CLOVER"), ("SQUARE", "SQUARE")],
                        default=None,
                        max_length=10,
                        null=True,
                    ),
                ),
                ("status", models.CharField(default="SUCCESS", max_length=20)),
                ("quantity", models.IntegerField(default=0)),
                ("time_limit", models.DateTimeField(blank=True, null=True)),
                (
                    "reservation_code",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("order_time", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservations",
                        to="inventories.customer",
                    ),
                ),
                (
                    "retailer",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservations",
                        to="retailer.retailer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated date"),
                ),
                ("quantity", models.IntegerField(default=0)),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "variation_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="inventories.order",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="inventories.variant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reservation Item",
                "verbose_name_plural": "Reservation Items",
            },
        ),
        migrations.CreateModel(
            name="OrderPickup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated date"),
                ),
                (
                    "recipient_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("pickup_time", models.DateTimeField(blank=True, null=True)),
                (
                    "origin_id",
                    models.CharField(
                        default=None, max_length=50, null=True, unique=True
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservation_pickups",
                        to="inventories.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pickup",
                "verbose_name_plural": "Pickup",
            },
        ),
        migrations.RemoveField(
            model_name="reservationpickup",
            name="reservation",
        ),
        migrations.AlterModelOptions(
            name="reservation",
            options={},
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="order_time",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="retailer",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="subtotal",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="tax",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="version",
        ),
        migrations.AddField(
            model_name="reservation",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventories.variant",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="origin_id",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservation_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name="ReservationItem",
        ),
        migrations.DeleteModel(
            name="ReservationPickup",
        ),
    ]
