# Generated by Django 4.2.3 on 2024-10-15 15:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventories", "0052_order_orderitem_orderpickup_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="reservation_code",
            new_name="order_code",
        ),
    ]
