# Generated by Django 4.2.3 on 2024-10-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventories", "0053_rename_reservation_code_order_order_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="origin_id",
            field=models.CharField(default=None, max_length=50, null=True, unique=True),
        ),
    ]
