# Generated by Django 4.2.3 on 2024-10-17 04:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventories", "0056_variantcategory_delete_productcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="variants",
            field=models.ManyToManyField(
                blank=True, related_name="categories", to="inventories.variant"
            ),
        ),
        migrations.DeleteModel(
            name="VariantCategory",
        ),
    ]
