# Generated by Django 4.2.3 on 2024-10-17 04:49

from django.db import migrations

# Generated by Django 4.2.3 on 2024-10-17 04:46

from django.db import migrations, models


def delete_old_rows(apps, scheme_editor):
    model = apps.get_model('inventories', 'Category')
    model.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("inventories", "0057_category_variants_delete_variantcategory"),
    ]

    operations = [
        migrations.RunPython(delete_old_rows),
    ]
