# Generated by Django 4.2.3 on 2024-10-17 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("retailer", "0017_remove_retailer_is_approved_retailer_note_and_more"),
        ("inventories", "0058_auto_20241017_0449"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="retailer",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="retailer.retailer",
            ),
            preserve_default=False,
        ),
    ]
