# Generated by Django 4.2.3 on 2024-11-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventories", "0059_category_retailer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-order_time"],
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
        migrations.AlterModelOptions(
            name="reservation",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="variant",
            name="sku",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="variant",
            name="upc",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
