# Generated by Django 4.2.3 on 2024-11-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventories", "0060_alter_order_options_alter_reservation_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variantimage",
            name="image_id",
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
