# Generated by Django 4.2.3 on 2024-11-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventories", "0061_alter_variantimage_image_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variantimage",
            name="image",
            field=models.ImageField(
                blank=True, max_length=511, null=True, upload_to="inventories"
            ),
        ),
    ]
