# Generated by Django 4.2.3 on 2024-12-05 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventories", "0062_alter_variantimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="item_type",
            field=models.CharField(
                choices=[(1, "Item"), (2, "Custom Amount")], default=1, max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="variant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items",
                to="inventories.variant",
            ),
        ),
    ]
