# Generated by Django 4.2.3 on 2024-12-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventories", "0063_orderitem_item_type_alter_orderitem_variant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="item_type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Item"), (2, "Custom Amount")], default=1, max_length=20
            ),
        ),
    ]
